export const CHARACTERS = [
  { id: 1, name: "aki" },
  { id: 2, name: "blanka" },
  { id: 3, name: "cammy" },
  { id: 4, name: "chunli" },
  { id: 5, name: "deejay" },
  { id: 6, name: "dhalsim" },
  { id: 7, name: "ed" },
  { id: 8, name: "ehonda" },
  { id: 9, name: "elena" },
  { id: 10, name: "gouki" },

  { id: 11, name: "guile" },
  { id: 12, name: "jamie" },
  { id: 13, name: "jp" },
  { id: 14, name: "juri" },
  { id: 15, name: "ken" },
  { id: 16, name: "kimberly" },
  { id: 17, name: "lily" },
  { id: 18, name: "luke" },
  { id: 19, name: "mai" },
  { id: 20, name: "manon" },

  { id: 21, name: "marisa" },
  { id: 22, name: "rashid" },
  { id: 23, name: "ryu" },
  { id: 24, name: "terry" },
  { id: 25, name: "vega" },
  { id: 26, name: "zangief" },
] as const;

export const CHARACTERS_NAME = [
  "aki",
  "blanka",
  "cammy",
  "chunli",
  "deejay",
  "dhalsim",
  "ed",
  "ehonda",
  "elena",
  "gouki",
  "guile",
  "jamie",
  "jp",
  "juri",
  "ken",
  "kimberly",
  "lily",
  "luke",
  "mai",
  "manon",
  "marisa",
  "rashid",
  "ryu",
  "terry",
  "vega",
  "zangief",
];
